import { Dialog, DialogContent, DialogHeader, DialogTitle } from "@/components/ui/dialog";
import { Brain } from "lucide-react";

interface ExplanationModalProps {
  open: boolean;
  onClose: () => void;
  dealId: string;
  explanation: string;
}

export default function ExplanationModal({ open, onClose, dealId, explanation }: ExplanationModalProps) {
  return (
    <Dialog open={open} onOpenChange={onClose}>
      <DialogContent className="sm:max-w-lg bg-card border-border">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <div className="w-7 h-7 rounded-lg gradient-primary flex items-center justify-center">
              <Brain className="w-3.5 h-3.5 text-primary-foreground" />
            </div>
            AI Explanation — {dealId}
          </DialogTitle>
        </DialogHeader>
        <div className="mt-2 p-4 rounded-lg bg-secondary border border-border">
          <p className="text-sm leading-relaxed text-foreground">{explanation}</p>
        </div>
        <p className="text-xs text-muted-foreground mt-2">
          Generated by DealMind AI Explainer
        </p>
      </DialogContent>
    </Dialog>
  );
}
